version: '3'

services:
   app:
      build: .
      ports:
         -   '8080:8080'
      depends_on:
         -   mysql
      environment:
         -   SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bank?useTimezone=true&serverTimezone=America/Sao_Paulo
         -   SPRING_DATASOURCE_USERNAME=root
         -   SPRING_DATASOURCE_PASSWORD=123456789
   mysql:
      image: mysql
      restart: always
      ports:
         -   '3307:3306'
      environment:
         -   MYSQL_ROOT_PASSWORD=123456789