openapi: 3.0.0
info:
  description: Money Box API
  version: 1.0.0
  title: Money Box
servers:
  - url: http://localhost:8080/api
paths:
  /account:
    get:
      summary: "Get an account"
      parameters:
        - in: query
          name: id
          schema:
            type: string
          required: false
          description: Account's id

    post:
      summary: "Create an account"
    patch:
      summary: "Close an account"
  /deposit:
    post:
      summary: "Make a deposit"
  /withdraw:
    post:
      summary: "Make a withdraw"
  /transter:
    post:
      summary: "Make a tranfer"
  /movement:
    get:
      summary: "Account movement"
      parameters:
        - in: query
          name: id
          schema:
            type: string
          required: required
          description: Account's id
        - in: query
          name: by
          schema:
            type: string
            enum: [date, value]
          required: false
          description: Sort movement
